name: Container
on: push

jobs:
  docker-step:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: log node version
        run: node -v
      - name: Step with container
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: '/bin/echo'
          args: 'Hello World'
      - name: Log node version
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: '/usr/local/bin/node'
          args: -v
      - uses: actions/checkout@v2
      - name: Run a script
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: ./newscript.sh
          args: "Some String"
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - "3001:3000"
      mongo:
          image: mongo
          ports:
            - "27017:27017"
    steps:
      - name: Log node version
        run : |
          node -v
          cat /etc/os-release